-- funcionalidades/ejercicio-017 - maria-montepeque
USE campuslands_mysql;

INSERT INTO formulas_quimicas (codigo, nombre, descripcion, categoria, fecha_registro) VALUES
    ('FQ-001', 'Acido Sulfurico Concentrado',
        'Compuesto altamente corrosivo utilizado en la industria de fertilizantes y en procesos de refinacion de petroleo. Reacciona de forma exotermica con el agua y debe almacenarse en recipientes resistentes a la corrosion.',
        'Acido', '2026-01-05'),
    ('FQ-002', 'Hidroxido de Sodio',
        'Base fuerte empleada en la fabricacion de jabon y en el tratamiento de aguas residuales. Absorbe humedad del ambiente y genera calor al disolverse en agua.',
        'Base', '2026-01-08'),
    ('FQ-003', 'Cloruro de Sodio Purificado',
        'Sal de mesa obtenida por evaporacion de salmuera. Se utiliza como conservante alimentario y como materia prima para la produccion de cloro e hidroxido de sodio mediante electrolisis.',
        'Sal', '2026-01-12'),
    ('FQ-004', 'Etanol Anhidro',
        'Alcohol de alta pureza usado como solvente en sintesis organica y como combustible renovable. Es inflamable y debe manejarse lejos de fuentes de ignicion.',
        'Solvente', '2026-01-15'),
    ('FQ-005', 'Acido Acetico Glacial',
        'Componente principal del vinagre en su forma concentrada. Se emplea en la produccion de acetato de celulosa y como reactivo en reacciones de esterificacion.',
        'Acido', '2026-01-20'),
    ('FQ-006', 'Amoniaco Anhidro',
        'Gas incoloro de olor penetrante utilizado en la fabricacion de fertilizantes nitrogenados. Requiere ventilacion adecuada por su toxicidad a altas concentraciones.',
        'Base', '2026-02-01'),
    ('FQ-007', 'Peroxido de Hidrogeno',
        'Agente oxidante utilizado como desinfectante y blanqueador. Se descompone en agua y oxigeno, liberando calor durante la reaccion catalitica.',
        'Oxidante', '2026-02-05'),
    ('FQ-008', 'Metanol Industrial',
        'Alcohol simple usado como disolvente y como materia prima en la sintesis de formaldehido. Es toxico si se ingiere o se inhala en espacios cerrados.',
        'Solvente', '2026-02-10'),
    ('FQ-009', 'Acetona Tecnica',
        'Cetona volatil ampliamente usada como disolvente de resinas y pinturas. Se evapora rapidamente y es altamente inflamable en presencia de chispas.',
        'Solvente', '2026-02-14'),
    ('FQ-010', 'Bicarbonato de Sodio',
        'Compuesto alcalino suave utilizado en la industria alimentaria y en formulaciones antiacidas. Neutraliza acidos de forma controlada sin generar residuos toxicos.',
        'Sal', '2026-02-18'),
    ('FQ-011', 'Acido Clorhidrico Diluido',
        'Acido fuerte empleado en la limpieza de superficies metalicas y en la regulacion de pH industrial. Genera vapores irritantes al entrar en contacto con el aire humedo.',
        'Acido', '2026-02-22'),
    ('FQ-012', 'Glicerina Refinada',
        'Subproducto de la saponificacion utilizado como humectante en cosmeticos y como materia prima en la sintesis de nitroglicerina para uso farmaceutico.',
        'Otro', '2026-02-25');
